---
title: "NBA and the Mid-Range"
author: "Pranav Vogeti"
date: "2024-01-07"
output: 
  html_document:
    css: customOutputScript.css
    toc: true
    toc_float: true
---

```{r message = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(lubridate)
library(kableExtra)
library(sportyR)
```


# Introduction

As we inch closer to the NBA All-Star Game, a game of absent defense and HIGH scoring offense, I was interested in analyzing how the Mid-Range shot in the NBA has evolved over time.


### The Focus Question

How has the mid-range shot in the NBA changed over time, and are there any influences that have mediated this particular shot's volume?

### Motivation

There are many different types of offensive plays in the NBA. Some plays are designed for guards to drive the ball into the basket. Some plays are designed for a quick three point shot. Some plays are designed to wear out the defense before making a decision on what shot to take. 

There are different types of shots in an NBA game. The dunk, the layup, paint shots, the free throw, the three point shot, and the focus of this report: the mid-range. In the early years of the modern NBA (80s-90s), the three point shot was more or less a privilege and an advantage for the undersized guard. Offenses at that time were largely based on physicality and paint-presence. Not many three point shots were taken and were treated as fall back options. Interestingly, if one were to turn on an NBA game now, that is not the case. Even the NBA's big men have developed a competitve jump shot to add an extra dynamicism to their offensive capabilities. Players like Nikola Jokić, Karl-Anthony Towns, Brook Lopez, Joel Embiid, and many other counterparts are prime examples of this evolution. In fact, in the 2022 three point contest, it was the big man Karl-Anthony Towns that won the infamous shooting contest! Towns was only the third big man to do so, behind very famous players like Dirk Nowitzki and Kevin Love. [^1]

[^1]: https://sports.yahoo.com/minnesota-timberwolves-center-karl-anthony-towns-wins-nba-all-star-3-point-contest-025319348.html

The three point shot has become so commonplace that it is hard to find plays that use the mid-range. If the league's big men have credible three-point shots, defenses get spread out in the half-court as now every offensive player can get a three over a two. A spread out defense also leaves gaping holes that, when properly accounted for by the offense, allows guards to simply drive the ball to the paint for a layup, or dunk, or a chance at the free-throw line. Thus, it is worth investigating the presence (or lackthereof, potentially) of the mid-range and its relations to the three point shot. 

# Background

### About the Original Data: Play-by-Play

The author that has provided the data for us to use is Vladislav Shufinsky. He has compiled NBA play-by-play data from 1996-2022 and made it open-source on Kaggle to allow us to use it for excursions like this[^1].

[^1]: <https://www.kaggle.com/datasets/brains14482/nba-playbyplay-and-shotdetails-data-19962021/data>

The data set we will use will contain a whole season's log of play-by-play data from the 2021-2022 NBA season. While the entire dataset consists of four subdata sets, we will choose to use the data originally sourced from *data.nba.com* This means that we will use the files called "*datanba_YYYY.csv*" where YYYY is the season of choice. 

### The Key Variables

-   The key variables from the *Play-By-Play* we will use for this excursion:
    -   `cl` the time stamp at which the significant play occurred
    -   `de` the short form description of what the play was
    -   `locX` the x-coordinate location of the `de` play
    -   `locY` the y-coordinate location of the `de` play
    -   `hs` the home team total points at the `cl` moment
    -   `vs` the visiting team total points at the `cl` moment
    -   `pts` the pts scored by the respective `hs` or `vs` at the `cl` moment
    -   `PERIOD` the quarter of the game so as to distinct `cl`
    -   `GAME_ID` the numerical identifier of the game being played

### Assumptions and Unusuality

A giant aspect of this report relies on the location data: `locX` and `locY`. The way we define the type of shot performed agrees with the NBA standard. However, there are certainly edge cases where we classify a shot differently when compared to the actual scorekeeper's book. Such edge cases are rare, but can and will happen during this excursion. An example of this case can be found in Game 6 of the 2021 NBA Eastern Conference Finals, when the Bucks played the Nets. In that game, Kevin Durant took a shot that had merits to be a three, but was ruled as a two because of his shoe being on the three point line. We will interpret all shots that show on the lmarking lines as a two. 

Another aspect of this report is that we are not necessarily evaluating the player's position. This is more of a holistic look at the shot architecture rather than a case-by-case shot outlook. So, a shot taken at the three point line by a Center will be treated the exact same as that shot taken by a Point Guard. We are just interested in looking at a broad look at shot behavior without delving too much into particulars. 

### Report Intentions

The rest of this report will focus on cleaning the data to fit our needs, and analyzing said data and fostering meaningful observations and conclusions. 


# Analysis

### Data Cleanup

Here we will cleanup our data to fit our analysis needs. 

### Data Summaries

In this section we will display relevant summary statistics to get a sense of the data we are dealing with. 

[Placeholder]

### Analysis 1: 

[Placeholder]

### Analysis 2: 

[Placeholder]

# Discussion

In this section, we will discuss the results of our tests and models and their implications in the context of our question and also their broader implications and limitations. 

### Comparing the Graphs & Overall Conclusions

#### Graph Comparisons Discussion

[Placeholder]

### Shortcomings and Limitations


#### Limitation 1

[Placeholder]

#### Limitation 2

[Placeholder]

### Alternate Approaches


#### Alternate Approach 1

[Placeholder]

#### Alternate Approach 2

[Placeholder]
 
### Potential Future Directions

[Placeholder]

# References
